name: Build Authn service
permissions: 
  contents: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment to build"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - dev2
          - qa
          - qa2
          - stage
          - prod
      code_branch:
        description: "Branch to build"
        required: true
        default: "main"
      trivy_test_scan:
        description: "Run Trivy Test Scan"
        required: true
        type: boolean
        default: false

env:
  PROJECT: "crdc-datahub"
  SERVICE: "authn"
  ECR_REPO: "crdc-hub-authn"
  REGION: "us-east-1"
  export REGISTRY_URL="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$REGION.amazonaws.com"
  CODE_BRANCH: "${{ github.event.inputs.code_branch }}"
  export CODE_FOLDER="$PROJECT-$SERVICE"
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CODE_BRANCH }}
          submodules: true

      - name: Configure AWS Role to assume using OIDC authentication
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY_URL

      - name: Build Docker Image
        run: |
          echo "Building: $ECR_REPO:$CODE_BRANCH.${{ github.run_number }}"
          docker build --no-cache -t $REGISTRY_URL/$ECR_REPO:$CODE_BRANCH.${{ github.run_number }} .

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs.trivy_test_scan == 'true'

    steps:
      - name: Run Trivy Vulnerability Scan
        run: |
          echo "Testing Image with Trivy: $ECR_REPO:$CODE_BRANCH.${{ github.run_number }}"
          docker run --rm --name trivy -u root -v /var/run/docker.sock:/var/run/docker.sock aquasecurity/trivy:latest \
          image --exit-code 1 --severity HIGH,CRITICAL $REGISTRY_URL/$ECR_REPO:$CODE_BRANCH.${{ github.run_number }}

  push:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Push Docker Image to ECR
        run: |
          echo "Pushing: $ECR_REPO:$CODE_BRANCH.${{ github.run_number }}"
          docker push $REGISTRY_URL/$ECR_REPO:$CODE_BRANCH.${{ github.run_number }}
